#pragma kernel CSMain
#include "Assets/Scripts/Perlin.hlsl"

RWStructuredBuffer<float> Result;

[numthreads(257,257,1)]
  
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: Perlin Implementation

    fnl_state noise = fnlCreateState();
    noise.noise_type = FNL_NOISE_OPENSIMPLEX2;
    noise.fractal_type = FNL_FRACTAL_FBM;

    // Gather noise data
    
    Result[id.x] = fnlGetNoise2D(noise, id.x, id.y);
}